### ISSUE TITLE
using the plugin related questions

### ISSUE THREAD

**Issue by PavelPolyakov** [an-rahulpandey/cordova-plugin-dbcopy#1]
Hi,

I'm trying to use your plugin to copy the database for the further use, as I understand this is the easiest way to use the custom prepopulated databases in the application.

I've already managed doing the copy, but hope you would help me with the other questions as well :)

The questions are the next:
1. I've created my database with sqlitebrowser, the type is SQLite format 3. But the sqlite plugin states that it works with the web sql. Could you clarify - is it possible to use the SQLite format 3 databases in the cordova app?
2. How could we check beforehand if the database file exists in the destination (/Documents for ios and "idontknowwhere" for android), before we're trying to copy
3. How do you prepare your database for the application, if the format from the point 1 question is not possible to use. I'm asking because even when the database was copied, the sqlite plugin then says to me that the table doesn't exist.

Looking forward for your answers.

Regards,

**Comment by ykarthikreddy18** [comment]
pavel can you help me how to install this plugin

**Comment by n40jpj** [comment]
I've posted about this quite a lot recently, Nic kindly did a really good write up here: https://blog.nraboy.com/2015/01/deploy-ionic-framework-app-pre-filled-sqlite-db/

**Comment by ykarthikreddy18** [comment]
Thnku n40jpj...
here he said to use the plugin "" cordova plugin add https://github.com/brodysoft/Cordova-SQLitePlugin.git ""..
but can we use the plugin "" cordova plugin add org.apache.cordova.storage ""  for retrieving the data from db??

**Comment by an-rahulpandey** [comment]
org.apache.cordova.storage is a Storage API and is completely different than the SQLite Plugin.

**Comment by ykarthikreddy18** [comment]
oh..thnku rahul..

**Comment by ykarthikreddy18** [comment]
Hi,
 while im trying to run "" cordova plugin add https://github.com/brodysoft/Cordova-SQLitePlugin.git""
It is saying the 
Error: Command failed: C:\Windows\system32\cmd.exe /s /c "git clone "https://git
hub.com/brodysoft/Cordova-SQLitePlugin.git" "C:\Users\karthik\AppData\Local\Temp
\plugman\git\1423631880201""
Cloning into 'C:\Users\karthik\AppData\Local\Temp\plugman\git\1423631880201'...
fatal: The remote end hung up unexpectedly
error: RPC failed; result=7, HTTP code = 0

    at ChildProcess.exithandler (child_process.js:744:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Socket.<anonymous> (child_process.js:1176:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:476:12)

..
please help me

**Comment by an-rahulpandey** [comment]
The problem you are having is not related to this plugin. But still to solve the issue, download the GitHub repository on your local machine, then install the plugin using the local directory path where you just downloaded the plugin -

````
cordova plugin add -d "C:\path\to\cloned\repo"
````

**Comment by an-rahulpandey** [comment]
The problem you are having is not related to this plugin. But still to solve the issue, download the GitHub repository on your local machine, then install the plugin using the local directory path where you just downloaded the plugin -

````
cordova plugin add -d "C:\path\to\cloned\repo"
````
If you are issue is not relevant to the current discussion, then open the new issue and at current location. I see you already opened another issue, so use that thread instead of this. It helps other users to find the answer if they are having the same problems.

**Comment by an-rahulpandey** [comment]
The problem you are having is not related to this plugin. But still to solve the issue, download the GitHub repository on your local machine, then install the plugin using the local directory path where you just downloaded the plugin -

````
cordova plugin add -d "C:\path\to\cloned\repo"
````
If you are issue is not relevant to the current discussion, then open the new issue and at current location. I see you already opened another issue, so use that thread instead of this. It helps other users to find the answer if they are having the same problems.

**Comment by ykarthikreddy18** [comment]
Ok rahul
