### ISSUE TITLE
Warning: no rule to process file 

### ISSUE THREAD

**Issue by blattmann** [an-rahulpandey/cordova-plugin-dbcopy#25]
Hi Rahul,

in xcode I receive this warning when I create a debug-build:

warning: no rule to process file '/Library/WebServer/Documents/rcs/dev/platforms/ios/Myapp/Plugins/me.rahul.plugins.sqlDB/sqlDB.h' of type sourcecode.c.h for architecture arm64

Might this also be the reason why my copied database is empty?

I only have problems with iOS. Android is absolutely ok!

**Comment by an-rahulpandey** [comment]
The issue is not related to empty db and I think you have already solved it.
However to remove this warning, you have to remove the sqlDB.h file from the compile sources in project's target build settings in Xcode. Open project in Xcode and follow these steps - 

1) Select the project target
2) Select the Build Phases
3) Expand the Compile Source
4) Remove the Header file (sqlDB.h)
