### ISSUE TITLE
Copy from a different folder

### ISSUE THREAD

**Issue by pdring** [an-rahulpandey/cordova-plugin-dbcopy#51]
Hi,

When I push my application to the Ionic Dashboard, the www is not copied and so the database is not available when I run it from Ionic View. In Xcode and Android Studio, my test builds work perfectly. Is there a way to copy the database from the resources or src > assets folder?

Thanks.

**Comment by an-rahulpandey** [comment]
Very first version of the plugin used to do the same. Since everyone uses cli to build, it was not viable option so I had to remove that, but I will see if I can implement that feature.

**Comment by pdring** [comment]
Thanks!

**Comment by gatelli** [comment]
Hi,
I need to copy DB from a DB downloaded via filetransfer so that is stored in _cdvfile://localhost/persistent/path/to/downloads/_ (so in iOS it's something like _file:///var/mobile/Containers/Data/Application/.../Documents/path/to/downloads/_)
Is there a way to edit your ios and android file to force the directory to that, instead of /www ?
Thanks a lot, I'm stuck....
