### ISSUE TITLE
IOS dbCopy in iCloud documents folder

### ISSUE THREAD

**Issue by scervellera** [an-rahulpandey/cordova-plugin-dbcopy#9]
Hello,
I use this plugin to ship prepopulated db in my IOS app.
The problem is the destination folder: iCloud synced documents folder ! My last submission in appStore was rejectd because my db should not be in that folder. The best position for db should be cache directory or noSync library folder, but at the moment i cannot choose the destination of the copy.

**Comment by n40jpj** [comment]
Ok I have a working solution which I am just about to upload to Apple. This is taking some information from the above link, and from applying a bit of common sense.

Step 1 : Find the file SQLitePlugin.m and go to line 170 ish. Now put the below lines:

NSArray *paths = NSSearchPathForDirectoriesInDomains(NSLibraryDirectory, NSUserDomainMask, YES);
NSString *libraryDirectory = [paths objectAtIndex:0];
libraryDirectory = [libraryDirectory stringByAppendingString:@"/NoCloud"];
NSError *err = nil;
[self setAppDocsPath:libraryDirectory];

In place of :

NSString *docs = [NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES) objectAtIndex: 0];
NSLog(@"Detected docs path: %@", docs);
[self setAppDocsPath:docs];

What this does is to tell the SQLitePlugin where to look for your database. The bit you are still missing is to get dbcopy to copy the .db file from the resources directory into the correct directory on the phone. To do this I did the following:

Step 2: Find and open the plugin file sqlDB.m:

Find the below:

paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);
documentsDirectory = [paths objectAtIndex:0];

Replace with :

NSArray *paths = NSSearchPathForDirectoriesInDomains(NSLibraryDirectory, NSUserDomainMask, YES);
NSString *libraryDirectory = [paths objectAtIndex:0];
libraryDirectory = [libraryDirectory stringByAppendingString:@"/NoCloud"];

That's it your app is back into a working state and now uses the Library/NoCloud directory rather than the Documents directory on the iphone.

**Comment by scervellera** [comment]
Thank you for reply n40jpj!!
I'll try your workaround with my working project!

**Comment by an-rahulpandey** [comment]
I will add the iCloud sync functionality in the next version of the plugin. Also can you try this -

http://tiku.io/questions/1734785/phonegap-ios-prevent-documents-folder-backup-on-icloud

Try the third answer. I used it a while ago when my app was rejected because of the same reasons. I do not know if this will work in the current version of the File plugin. But you can give it a try instead of modifying the backup.

**Comment by remi-lebigre** [comment]
Hello scervellera,

My app was rejected from submission for the same reason (iCloud storage), so I used your fix up above.
The SQLitePlugin is now 1.0.4, I think it might have changed a bit, so I had to rewrite your fix to make it work :

I replaced the lines in SQLitePlugin.m by :
<pre><code>NSArray *paths = NSSearchPathForDirectoriesInDomains(NSLibraryDirectory, NSUserDomainMask, YES); 
NSString *libraryDirectory = [paths objectAtIndex:0];
libraryDirectory = [libraryDirectory stringByAppendingString:@"/NoCloud"];
NSError *err = nil;
NSLog(@"Detected libraryDirectory path: %@", libraryDirectory);
[appDBPaths setObject: libraryDirectory forKey:@"libraryDirectory"];
</code></pre>

and on the sqlDB.m :
remove your part plus :
<pre><code>NSString *dbPath = [documentsDirectory stringByAppendingPathComponent:dbname]</code></pre>
and add :
<pre><code>paths = NSSearchPathForDirectoriesInDomains(NSLibraryDirectory, NSUserDomainMask, YES);
NSString *libraryDirectory = [paths objectAtIndex:0];
libraryDirectory = [libraryDirectory stringByAppendingString:@"/NoCloud"];
NSString *dbPath = [libraryDirectory stringByAppendingPathComponent:dbname];</code></pre>
This worked perfectly for me

**Comment by an-rahulpandey** [comment]
Updated the plugin
